---
title: "Module 0: Introduction"
linktitle: "M0: Overview"
menu:
  content:
    parent: Module 0
    weight: 1
type: docs
bibliography: "../../static/bib/BibTeX_Library.bib"
csl: "../../static/bib/chicago-syllabus-no-bib.csl"
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
```

This introduction module is a time for us to go over the details of the course, set up all of the software needs, and perform some basic data management and summary statistics. We'll also introduce the idea of causal inference and define the treatment effect estimands that will be of central interest throughout the course.

## Readings and other links

- Review the [syllabus](/syllabus/), [schedule](/schedule/), [content](/content/), and [assignments](/assignment/) pages for this class...just to get a feel for the site and how to navigate all of the information.
- <i class="fas fa-book"></i> Materials we'll use throughout this module:
    - Lesson 2 from [Data Science for Economists](https://github.com/uo-ec607/lectures). This is part of a course from [Grant McDermott](https://grantmcdermott.com/) with a ton of great online resources.
    - [R for Data Science](https://r4ds.had.co.nz/)
    - Understand filepaths. Short [video](https://youtu.be/NG7Y0kkGR8g) from Nick Huntington-Klein.
    - Chapter 5 of [Causal Inference: The Mixtape](https://mixtape.scunning.com/)
    - Chapter 14 of [The Effect: An Introduction to Research Design and Causality](https://theeffectbook.net/)
- <i class="fa fa-database"></i> Data for this module:
    - Data from [Gapminder](https://www.gapminder.org/)
    - [Medicare Advantage](https://github.com/imccart/ma-class) repository

