---
title: Expectations
date: "2022-1-03"
menu:
  content:
    parent: Overview
    weight: 2
type: docs
weight: 2
---

Please come to class prepared and ready to participate. Attendance is very important for this class because we don't have a single textbook source that covers everything. That said, life happens and I completely understand that. I've tried to structure the grading so that attendance is incentivized without any unnecessary punishment for exceptions. 

This class is very applied in nature. Almost everything we do will involve some real data. Many of you may have extensive experience working with data but very little experience working with "real" data (meaning, data that haven't already been cleaned and organized for you). Making this transition will come with some growing pains, but...I am a resource for you, and I will be available as much as possible to help you throughout the semester. Of course, I can't help you if you don't reach out to me, and I definitely can't help you if you only reach out a few hours before the due date of an assignment or a couple of days prior to the final project. 

So...here are my rules to be successful in this class:

1. Attend and participate in class
2. Do all of the in-class exercises on your own
3. Work through all of the examples from the online textbooks
4. Start on the homework assignments and the project early
5. Ask me questions! and discuss with your classmates!