---
title: "Homework 5"
linktitle: "Homework 5"
due_date: "2022-04-25"
due_time: "11:59 PM"
output:
  blogdown::html_page:
    toc: false
menu:
  assignment:
    parent: Homework
    weight: 5
type: docs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

# Instructions
In this assignment, you'll recreate the Insurance and Medicaid Expansion data and answer a few questions along the way. As with the prior assignments, the first step is to make sure you have the [Insurance Access repository](https://github.com/imccart-ma/medicaid) and downloaded all of the raw data sources. Once you have the data downloaded and the code running, answer the following questions:

# Summarize the data
1. Plot the share of insured individuals with direct purchase health insurance over time.
2. Discuss the reduction in direct purchase health insurance in later years. Can you list a couple of policies that might have affected the success of the direct purchase insurance market?
3. Plot the share of insured individuals with Medicaid over time.
4. Plot the share of uninsured over time, separately by states that expanded Medicaid in 2014 versus those that did not. Drop all states that expanded after 2014.


# Estimate ATEs
For the rest of the assignment, we're going to apply the difference-in-differences estimator to the question of Medicaid expansion and uninsurance.

1. Calculate the average percent of uninsured individuals in 2012 and 2015, separately for expansion and non-expansion states. Present your results in a basic 2x2 DD table.
2. Estimate the effect of Medicaid expansion on the uninsurance rate using a standard DD regression estimator, again focusing only on states that expanded in 2014 versus those that never expanded.
3. Include state and year *fixed effects* in your estimates. Try using the `lfe` or `fixest` package to estimate this instead of directly including the fixed effects.
4. Repeat the analysis in question 3 but include all states (even those that expanded after 2014). Are your results different? If so, why?
5. Provide an "event study" graph showing the effects of Medicaid expansion in each year. Use the specification that includes state and year fixed effects, limited to states that expanded in 2014 or never expanded.
6. Repeat part 5 but again include states that expanded after 2014. Note: this is tricky...you need to put all states onto "event time" to create this graph.
